### PR TITLE
fix(config): Removes disable_account_registration from database

### LINKED ISSUE #240: disable_account_registration present in settings table
This needs to be removed with a migration. When HM is first booted, it seeds the app.yml file into the settings table, thus, disable_account_registration is still present until we remove the record.

### PR DESCRIPTION
**Pull request by cbaudouinjr**
fixes #240

### CODE REVIEW

File: db/migrate/20200530172450_delete_disable_account_registration_from_settings.rb [hunk 1]
```diff
@@ -0,0 +1,11 @@
+class DeleteDisableAccountRegistrationFromSettings < ActiveRecord::Migration[5.2]
+  def self.up
+    return unless HackathonConfig.find_by(var: 'disable_account_registration').present?
+    HackathonConfig.find_by(var: 'disable_account_registration').destroy
+  end
+
+  def self.down
+    return unless HackathonConfig.find_by(var: 'disable_account_registration').nil?
+    HackathonConfig.create(var: 'disable_account_registration', value: false).save
```
Comment (peterkos) [inline db/migrate/20200530172450_delete_disable_account_registration_from_settings.rb:9]: Wouldn't this not restore any previously set value? Or does it not matter?

Comment (cbaudouinjr) [reply db/migrate/20200530172450_delete_disable_account_registration_from_settings.rb:9]: Shouldn't matter and we'd have to hang on to the old value somewhere.
